[[runners]]
  name = "runner-docker"
  url = "http://gitlab:80"
  token = "glrt-Yq5ADRtJp5oFdaR4cmbqFW86MQp0OjEKdToxCw.01.1205v0k66"
  executor = "docker"

  [runners.docker]
    image = "docker:27"
    privileged = true
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
